version: '3.7'
services:
  dlife-h5:
    image: naice/dlife-h5:latest
    ports:
      - 3333:80
    networks:
      - main-network
    restart: unless-stopped

  dlife-develop-h5:
    image: naice/dlife-develop-h5:latest
    ports:
      - 3336:80
    networks:
      - main-network
    restart: unless-stopped

  dlifeServerH5:
      image: naice/dlife-server-h5:latest
      ports:
        - 3335:3335
      networks:
        - main-network
      volumes:
        - /home/leo/web-logs:/usr/src/app/logs
      restart: unless-stopped

networks:
    main-network: