import { http } from '~/utils/http'

export const chatApi = {
  // 获取 不用登录的聊天详情
  getChatHistoryList(payload: IChatHistoryListParams) {
    return http.get<IChatHistoryList>(
      '/sys/chatContent/page',
      payload,
    )
  },
}

export interface IChatHistoryListParams {
  current: number
  pageSize: number
  userId: string
}

// Generated by https://quicktype.io

export interface IChatHistoryList {
  code: number
  msg: string
  data: Data
}

export interface Data {
  total: number
  list: IChatHistoryListItem[]
}

export interface IChatHistoryListItem {
  fromId: string
  content: string
  toId: string
  chatTime: number
  fileUrl: string
  isRead: null
  duration: number
  moduleCode: null
  moduleResult: null
}
