name: Pack Docker Image CI

env:
  DOCKER_TAG: naice/star-beta-dev-h5:latest

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . -f devops/Dockerfile.develop --tag $DOCKER_TAG

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push $DOCKER_TAG
